title: MoVeR | Effective Programming
description: >
  MoVeR Documentation
baseurl: "/mover"
url: "http://effectiveprogramming.github.io"
twitter_username: LutherBaker
github_username:  EffectiveProgramming

# Build settings
markdown: kramdown
